# Generated by Django 4.1.3 on 2022-11-29 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
