# Generated by Django 4.1.3 on 2022-12-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_message_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='name_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
